#!/Users/moff/.nodebrew/current/bin/node

let fs = require("fs");
let Phrase = require("moff-palindrome");

// 検出されたパリンドロームの格納先
let palindromePhrases = [];

let text = fs.readFileSync("phrases.txt", "utf-8");
text.split("\n").forEach((line) => {
  let phrase  = new Phrase(line);
  if (phrase.palindrome()) {
    console.log("検出されたパリンドローム: ", line);
    palindromePhrases.push(line);
  }
});

fs.writeFileSync("palindromes.txt", palindromePhrases.join("\n"), "utf-8");
console.log("ファイルを保存しました。");