#!/Users/moff/.nodebrew/current/bin/node

let urllib = require("urllib");
let Phrase = require("moff-palindrome");
let url = 'https://cdn.learnenough.com/phrases.txt'

async function fetchPalindromes() {
  let { error, data, response } = await urllib.request(url, { followRedirect: true });
  let body = data.toString();
  let lines = body.split('\n');

  let palindromes = lines.filter((line) => {
    let phrase = new Phrase(line);
    return phrase.palindrome();
  });
  
  palindromes.forEach((palindrome) => {
    console.log('検出されたパリンドローム:', palindrome);
  });
}

fetchPalindromes();